# Generated by Django 6.0.6 on 2026-06-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha_temporaria',
            field=models.BooleanField(default=False, verbose_name='senha temporária'),
        ),
    ]
