# Generated by Django 6.0.6 on 2026-06-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_senha_temporaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cuidador',
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
