# Generated by Django 5.2.15 on 2026-06-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_familiar_usuario_delete_cuidador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='estado (UF)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União estável')], max_length=15, verbose_name='estado civil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='avatares/', verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('outro', 'Outro'), ('nao_informar', 'Prefiro não informar')], max_length=15, verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=60, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='rua'),
        ),
    ]
