# Generated by Django 6.0.6 on 2026-06-18 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_participacao_token_participacao_vinculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10, verbose_name='turno')),
                ('tipo_padrao', models.CharField(choices=[('rodizio', 'Rodízio'), ('semanal', 'Por dia da semana')], default='rodizio', max_length=10, verbose_name='tipo de padrão')),
                ('dias_por_pessoa', models.PositiveSmallIntegerField(default=1, verbose_name='dias por pessoa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='início do rodízio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padroes_escala', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'padrão de turno',
                'verbose_name_plural': 'padrões de turno',
                'db_table': 'padrao_turno',
            },
        ),
        migrations.CreateModel(
            name='RodizioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rodizio', to='escala.padraoturno')),
            ],
            options={
                'db_table': 'rodizio_item',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SemanalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('cuidador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_semanal', to='escala.padraoturno')),
            ],
            options={
                'db_table': 'semanal_item',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='ExcecaoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10, verbose_name='turno')),
                ('cuidador', models.ForeignKey(blank=True, help_text='Vazio = folga (ninguém).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes_escala', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'exceção de dia',
                'verbose_name_plural': 'exceções de dia',
                'db_table': 'excecao_dia',
                'constraints': [models.UniqueConstraint(fields=('paciente', 'data', 'turno'), name='unique_excecao_dia')],
            },
        ),
        migrations.AddConstraint(
            model_name='padraoturno',
            constraint=models.UniqueConstraint(fields=('paciente', 'turno'), name='unique_padrao_turno'),
        ),
        migrations.AddConstraint(
            model_name='semanalitem',
            constraint=models.UniqueConstraint(fields=('padrao', 'dia_semana'), name='unique_semanal_dia'),
        ),
    ]
