# Generated by Django 5.2.15 on 2026-06-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_participacao_token_participacao_vinculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacoes', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='pacientes.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'anotação',
                'verbose_name_plural': 'anotações',
                'db_table': 'anotacao',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['paciente', 'data_hora'], name='idx_anotacao_pac_data')],
            },
        ),
    ]
