# Generated by Django 5.2.15 on 2026-06-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_participacao_token_participacao_vinculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantao', models.DateField(verbose_name='data do plantão')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='hora de entrada')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='hora de saída')),
                ('localizacao_gps_entrada', models.CharField(blank=True, max_length=100, verbose_name='GPS de entrada')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10, verbose_name='status')),
                ('duracao_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='duração (horas)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantoes', to=settings.AUTH_USER_MODEL, verbose_name='cuidador')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes', to='pacientes.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'plantão',
                'verbose_name_plural': 'plantões',
                'db_table': 'plantao',
                'ordering': ['-data_plantao', '-hora_entrada'],
                'constraints': [models.UniqueConstraint(fields=('paciente', 'cuidador', 'data_plantao'), name='unique_plantao_aberto')],
            },
        ),
    ]
