# Generated by Django 6.0.6 on 2026-06-17 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame')], default='consulta', max_length=10, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('profissional', models.CharField(blank=True, max_length=255, verbose_name='profissional/local')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='endereço/local')),
                ('crm', models.CharField(blank=True, max_length=50, verbose_name='CRM')),
                ('convenio', models.CharField(blank=True, max_length=100, verbose_name='convênio')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=10, verbose_name='status')),
                ('resultado', models.TextField(blank=True, verbose_name='resultado')),
                ('realizada_em', models.DateTimeField(blank=True, null=True, verbose_name='realizada em')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('agendada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_agendadas', to=settings.AUTH_USER_MODEL, verbose_name='agendada por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente', verbose_name='paciente')),
                ('realizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='realizada por')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'db_table': 'consulta',
                'ordering': ['data_hora'],
                'indexes': [models.Index(fields=['paciente', 'data_hora'], name='idx_consulta_pac_data'), models.Index(fields=['status'], name='idx_consulta_status')],
            },
        ),
    ]
