# Generated by Django 6.0.6 on 2026-06-17 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='profissional',
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='medicos.medico', verbose_name='médico/clínica'),
        ),
    ]
