# Generated by Django 6.0.6 on 2026-06-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_remove_consulta_convenio_remove_consulta_crm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='local',
        ),
    ]
