# Generated by Django 6.0.6 on 2026-06-16 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='remédio')),
                ('dosagem', models.CharField(max_length=50, verbose_name='dosagem')),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100, verbose_name='forma farmacêutica')),
                ('frequencia', models.CharField(blank=True, max_length=100, verbose_name='frequência')),
                ('horarios', models.CharField(blank=True, help_text='Horários separados por vírgula (ex.: 08:00, 20:00).', max_length=255, verbose_name='horários')),
                ('quantidade_dose', models.CharField(blank=True, max_length=50, verbose_name='quantidade por dose')),
                ('medico', models.CharField(blank=True, max_length=255, verbose_name='médico')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco para uso contínuo.', null=True, verbose_name='data de fim')),
                ('seg', models.BooleanField(default=True, verbose_name='segunda')),
                ('ter', models.BooleanField(default=True, verbose_name='terça')),
                ('qua', models.BooleanField(default=True, verbose_name='quarta')),
                ('qui', models.BooleanField(default=True, verbose_name='quinta')),
                ('sex', models.BooleanField(default=True, verbose_name='sexta')),
                ('sab', models.BooleanField(default=True, verbose_name='sábado')),
                ('dom', models.BooleanField(default=True, verbose_name='domingo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observação')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('descontinuado', 'Descontinuado')], default='ativo', max_length=15, verbose_name='status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pacientes.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
                'db_table': 'medicamento',
                'ordering': ['data_inicio', 'nome'],
            },
        ),
    ]
