# Generated by Django 6.0.6 on 2026-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='data de início'),
        ),
    ]
