# Generated by Django 6.0.6 on 2026-06-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_alter_medicamento_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da dose')),
                ('horario', models.CharField(max_length=5, verbose_name='horário')),
                ('tomado_em', models.DateTimeField(auto_now_add=True, verbose_name='tomado em')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_dose', to='medicamentos.medicamento', verbose_name='medicamento')),
            ],
            options={
                'verbose_name': 'registro de dose',
                'verbose_name_plural': 'registros de dose',
                'db_table': 'registro_dose',
                'ordering': ['data', 'horario'],
                'indexes': [models.Index(fields=['medicamento', 'data'], name='idx_dose_med_data')],
                'constraints': [models.UniqueConstraint(fields=('medicamento', 'data', 'horario'), name='uq_dose_med_data_horario')],
            },
        ),
    ]
