# Generated by Django 6.0.6 on 2026-06-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_registrodose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoTomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da dose')),
                ('horario_previsto', models.CharField(max_length=5, verbose_name='horário previsto')),
                ('tomado', models.BooleanField(default=True, verbose_name='tomado')),
                ('tomado_em', models.DateTimeField(blank=True, null=True, verbose_name='marcado como tomado em')),
            ],
            options={
                'verbose_name': 'medicamento tomado',
                'verbose_name_plural': 'medicamentos tomados',
                'db_table': 'medicamento_tomado',
                'ordering': ['data', 'horario_previsto'],
            },
        ),
        migrations.RemoveIndex(
            model_name='registrodose',
            name='idx_dose_med_data',
        ),
        migrations.RemoveConstraint(
            model_name='registrodose',
            name='uq_dose_med_data_horario',
        ),
        migrations.AddField(
            model_name='medicamentotomado',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tomado', to='medicamentos.medicamento', verbose_name='medicamento'),
        ),
        migrations.RemoveField(
            model_name='registrodose',
            name='medicamento',
        ),
        migrations.AddIndex(
            model_name='medicamentotomado',
            index=models.Index(fields=['medicamento', 'data'], name='idx_tomado_med_data'),
        ),
        migrations.AddConstraint(
            model_name='medicamentotomado',
            constraint=models.UniqueConstraint(fields=('medicamento', 'data', 'horario_previsto'), name='uq_tomado_med_data_horario'),
        ),
        migrations.DeleteModel(
            name='RegistroDose',
        ),
    ]
