# Generated by Django 6.0.6 on 2026-06-17 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_medicamentotomado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentotomado',
            name='marcado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doses_marcadas', to=settings.AUTH_USER_MODEL, verbose_name='marcado por'),
        ),
    ]
