# Generated by Django 6.0.6 on 2026-06-15 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='telefone')),
                ('condicoes_saude', models.TextField(blank=True, verbose_name='condições de saúde')),
                ('alergias', models.TextField(blank=True, verbose_name='alergias')),
                ('foto', models.CharField(blank=True, max_length=255, verbose_name='foto')),
                ('latitude_gps', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_gps', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('raio_validacao_gps', models.FloatField(default=100, verbose_name='raio de validação (m)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('familiar_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='familiar responsável')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'db_table': 'paciente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_participacao', models.CharField(choices=[('familiar', 'Familiar'), ('cuidador', 'Cuidador')], max_length=10)),
                ('status_convite', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('data_convite', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('permissao_leitura', models.BooleanField(default=True)),
                ('permissao_escrita', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='pacientes.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'db_table': 'participacao',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'paciente'), name='unique_participacao')],
            },
        ),
    ]
