# Generated by Django 6.0.6 on 2026-06-17 23:04

import pacientes.models
from django.db import migrations, models
from django.utils.crypto import get_random_string


def gerar_tokens(apps, schema_editor):
    """Garante um token único para cada participação já existente."""
    Participacao = apps.get_model("pacientes", "Participacao")
    for participacao in Participacao.objects.all():
        participacao.token = get_random_string(40)
        participacao.save(update_fields=["token"])


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='vinculo',
            field=models.CharField(blank=True, max_length=100, verbose_name='vínculo'),
        ),
        # 1) Adiciona o token sem unicidade (mesmo default p/ todas as linhas).
        migrations.AddField(
            model_name='participacao',
            name='token',
            field=models.CharField(default=pacientes.models._novo_token, max_length=40, verbose_name='token do convite'),
        ),
        # 2) Popula um token único por linha existente.
        migrations.RunPython(gerar_tokens, migrations.RunPython.noop),
        # 3) Aplica a restrição de unicidade.
        migrations.AlterField(
            model_name='participacao',
            name='token',
            field=models.CharField(default=pacientes.models._novo_token, max_length=40, unique=True, verbose_name='token do convite'),
        ),
    ]
