# Generated by Django 5.2.15 on 2026-06-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_cep_paciente_cidade_paciente_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='pacientes/', verbose_name='foto'),
        ),
    ]
