# Generated by Django 6.0.6 on 2026-06-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('medico', 'Médico'), ('clinica', 'Clínica'), ('laboratorio', 'Laboratório')], default='medico', max_length=15, verbose_name='tipo')),
                ('especialidade', models.CharField(blank=True, max_length=150, verbose_name='especialidade')),
                ('crm_cnpj', models.CharField(blank=True, max_length=50, verbose_name='CRM/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='e-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='pacientes.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'db_table': 'medico',
                'ordering': ['nome'],
            },
        ),
    ]
