# Generated by Django 6.0.6 on 2026-06-17 04:58

import django.db.models.deletion
import familia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('vinculo', models.CharField(max_length=100, verbose_name='vínculo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito')], default='pendente', max_length=10, verbose_name='status')),
                ('token', models.CharField(default=familia.models._novo_token, max_length=40, unique=True, verbose_name='token do convite')),
                ('data_convite', models.DateTimeField(auto_now_add=True, verbose_name='convite enviado em')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('convidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_familia_enviados', to=settings.AUTH_USER_MODEL, verbose_name='convidado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_familia', to='pacientes.paciente', verbose_name='paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_familia', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro da família',
                'verbose_name_plural': 'membros da família',
                'db_table': 'membro_familia',
                'ordering': ['status', 'nome'],
                'indexes': [models.Index(fields=['paciente', 'status'], name='idx_membro_pac_status')],
            },
        ),
    ]
