# Generated by Django 6.0.6 on 2026-06-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membrofamilia',
            name='idx_membro_pac_status',
        ),
        migrations.DeleteModel(
            name='MembroFamilia',
        ),
    ]
